name: Waka Readme

on:
  schedule:
    - cron: '15 */12 * * *'
  workflow_dispatch:
  
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: fahmifareed/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: waka_76e2eba2-0f2b-4972-9e37-2f145e6a2653
          GH_TOKEN: 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
          SHOW_DAYS_OF_WEEK: False
          SHOW_LANGUAGE: False
