name: Waka Readme

on:
  schedule:
    - cron: '15 */12 * * *'
  workflow_dispatch:
  
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: miermontoto/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: waka_08b60642-208d-46b7-a880-1f2ec67e1938
          GH_TOKEN: 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
          SHOW_DAYS_OF_WEEK: False
          SHOW_LANGUAGE: False
